```{r}
library(jsonlite)
library(dplyr)
library(ggplot2)
library(directlabels)
library(memoise)
theme_set(theme_classic(16) +
theme(
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black")
  ))
```

# histogram of EIG values

read in json files

```{r}
json.filenames = (function(x) { x[grepl("json", x)] })(list.files())
dfs = Map(fromJSON, json.filenames)
```

extract eigs so far
```{r}
eigs = unname(unlist(Map(function(e) { e$EIG }, dfs)))
```

plot
```{r}
d.eig = data.frame(eig = eigs) 

breaks = seq(from = 0, to = 0.09, by = 0.01/2)

d.eigcut = d.eig %>%
  transform(bucket = cut(eig,
                         breaks = breaks,
                         labels = breaks[2:length(breaks)]
                         )) %>%
  transform(bucket = as.numeric(as.character(bucket))) %>%
  group_by(bucket) %>% summarise(count = n())

d.eigcut = d.eigcut %>% transform(Experiment = ifelse(bucket == 0.03, "MS",
                                                      ifelse(bucket == 0.085, "Optimal", "Other")))

d.eigcut$Experiment = factor(d.eigcut$Experiment, levels = levels(d.eigcut$Experiment)[c(2,1,3)])

ggplot(data = d.eigcut) + geom_bar(mapping = aes(x = bucket, y = count, fill = Experiment), stat = 'identity') + 
  ylab("Count") +
  xlab("Expected information gain") + 
  scale_x_continuous(limits = c(0,0.09), breaks = seq(from = 0, to = 0.09, by = 0.09 / 3)) + 
  scale_fill_manual(values = c("MS" = "red2", "Optimal" = "blue", "Other" = "grey60"))
```

# curve of AIGs vs subjects

```{r}
generic.ci_ <- function(x, n = 5000){
    structure(
        quantile(
            replicate(n, mean(sample(x, replace = TRUE),
                              na.rm = TRUE)),
            c(0.025, 0.975)),
        names=c("ci.l","ci.u"))
}

generic.ci <- memoise(generic.ci_)

ci.l <- function(x) {
  generic.ci(x)["ci.l"]
}

ci.u <- function(x) {
  generic.ci(x)["ci.u"]
}
```

todo: optimize CI time
```{r}
aigs = rbind(fromJSON("aig-curve-ms.json"),
             fromJSON("aig-curve-opt.json"))

aigs.agg = aigs %>%
  group_by(ex, n) %>%
  summarise(mean.aig = mean(aig),
            cl = ci.l(aig),
            cu = ci.u(aig)) %>%
  ungroup() %>%
  mutate(ex = factor(ifelse(ex == 'ms', 'MS','Optimal')))

aigs.agg$Experiment = factor(aigs.agg$ex, levels = rev(levels(aigs.agg$ex)))
```

(export as 6x3)
```{r}
qplot(data =  aigs.agg,
      x = n,
      y = mean.aig,
      ymin = cl,
      ymax = cu,
      color = Experiment,
      geom = c('point','errorbar','line')) + ylab("Actual information gain") + xlab("Number of participants") +
  scale_color_manual(values = c("MS" = "red2", "Optimal" = "blue", "Other" = "grey60"))

```


