```{r}
library(dplyr)
library(ggplot2)
library(directlabels)
theme_set(theme_classic(24))
```

# summarizing data so we can get AIG with webppl-oed

```{r}
d = read.csv("subjrand-1-trials.csv", stringsAsFactors = FALSE)
```


how many subjects get alloted to each cell?

```{r}
d %>% group_by(sequence) %>% summarise(n=n())
```

for each sequence, how many subjects say heads versus tails?
```{r}
d %>% group_by(sequence) %>% summarise(n.heads = sum(response == "H"), n.tails = sum(response == "T"))
```

# comparing expected and actual igs

# ig ~ eig


```{r}
di = read.csv('information-gains.csv')
```

plot ig versus eig:
```{r}
qplot(data = di, x = eig, y = ig)
```

direct labeled version:
```{r}
direct.label(qplot(data = di, x = eig, y = ig, color = experiment))
```

how well does eig model ig?
```{r}
summary(lm(data = di, formula = ig ~ eig))
```

(r^2 = 0.7)

# ig ~ eig.ignorance

plot ig versus eig.ignorance:
```{r}
qplot(data = di, x = eig.ignorance, y = ig)
```

direct labeled version:
```{r}
direct.label(qplot(data = di, x = eig.ignorance, y = ig, color = experiment))
```

```{r}
summary(lm(data = di, formula = ig ~ eig.ignorance))
```

R^2: 0.78
