---
title: "coins"
author: "mhtess and louyang"
date: "May 11, 2016"
output: html_document
---

Packages, helper functions, and plot theme

```{r echo=F}
#library(rwebppl)

corr_eqn <- function(x,y, digits = 2) {
  corr_coef <- round(cor(x, y)^2, digits = digits)
  paste("italic(r^2) == ", corr_coef)
}

theme_paper <- function(base_size = 12, base_family = "Helvetica") {
  theme(
    line =               element_line(colour = "black", 
                                      size = 0.5, linetype = 1,
                                      lineend = "butt"),
    rect =               element_rect(fill = "black", 
                                      colour = "black", 
                                      size = 0.5, linetype = 1),
    text =               element_text(family = base_family, face = "plain",
                                      colour = "black", size = base_size,
                                      hjust = 0.5, vjust = 0.5, 
                                      angle = 0, lineheight = 0.9,
                                      margin = margin(2,1,3,1), debug = FALSE),
    axis.text =          element_text(size = 12, 
                                      colour = "black", 
                                      margin=margin(1,1,1,1)),
    strip.text =         element_text(size = 12, 
                                      colour = "black", 
                                      margin=margin(1,1,4,1)),
    
    axis.line =          element_blank(),
    axis.ticks =         element_line(colour = "black", size = 0.2),
    axis.title =         element_text(colour = "black", size=16),
    axis.ticks.length =  unit(0.3, "lines"),

    legend.background =  element_rect(colour = "white", fill='white'),
    legend.margin =      unit(0.2, "cm"),
    legend.key =         element_rect(fill = "white", colour = "white"),
    legend.key.size =    unit(1.2, "lines"),
    legend.key.height =  NULL,
    legend.key.width =   NULL,
    legend.text =        element_text(size = rel(1.2), colour = "black"),
    legend.text.align =  NULL,
    legend.title =       element_text(size = rel(1.2), 
                                      face = "bold", hjust = 0, 
                                      colour = "black"),
    legend.title.align = NULL,
    legend.position =    "right",
    legend.direction =   "vertical",
    legend.justification = "center",
    legend.box =         NULL,
    
    panel.background =   element_rect(fill = "white", colour = NA),
    panel.border =       element_rect(fill = NA, colour = "black"),
    panel.grid.major =   element_line(colour = "white", size = 0.2),
    panel.grid.minor =   element_line(colour = "white", size = 0.5),
    panel.margin =       unit(0.5, "lines"),

    strip.background =   element_rect(fill = "white", colour = "white"),
    strip.text.x =       element_text(),
    strip.text.y =       element_text(angle = -90),
    
    plot.background =    element_rect(colour = "white", fill = "white"),
    plot.title =         element_text(size = rel(1.2)),
    plot.margin =        unit(c(1, 1, 0.5, 0.5), "lines"),
    
    complete = TRUE
  )
}

```



```{r}
#setwd("experiments/analysis")
d.human <-read.csv(file = "../data/coins-trials.csv")
d.eig <- read.csv(file = "../data/coins-eig-n1-n20.csv")
d.eig.curve <- read.csv(file = "../data/coins-eig-curve-3way.csv")
```


EIG by experiment

```{r, fig.width=11, fig.height=4}
d.eig %>% 
  filter(comparison != "fair-markov" & response_prior == "ignorance") %>%
  mutate(comparison = factor(comparison, 
                  levels = c("fair-bias", "bias-markov",
                                     "threeway"),
                  labels = c(
                    "fair vs. bias",
                    "bias vs. markov",
                    "fair vs. bias vs. markov"
                  ))) %>%
  rowwise() %>%
  mutate(eig = ifelse(eig < 0.005, 0.005, eig)) %>%
  ggplot(., aes(x = sequence, y = eig))+
    geom_bar(stat='identity', position=position_dodge())+
    coord_flip()+
    facet_wrap(~comparison)+
    ylab("Expected Information Gain from 20 participants")+
    xlab("Experiment")+
    guides(fill=F)+
  theme_paper()
  
#ggsave("writing/nips2016/img/coin_eig_n20_ignorance.pdf", height = 4, width = 11)
```

EIG by experiment and N

```{r, fig.width=5, fig.height=3.5}
experiments.of.interest<- c("HHHH", "HHHT", "HTHT")

d.eig.curve %>%
  filter(response_prior == "ignorance") %>%
  filter(seq%in%experiments.of.interest & n <= 30) %>%
  rename(Experiment = seq) %>%
  mutate(Experiment = factor(Experiment, levels=c("HTHT", "HHHT", "HHHH"))) %>%
ggplot(., aes(x=n, y=eig, 
                 color=Experiment, group=Experiment, linetype=Experiment))+
  geom_line(size=1.3)+
  scale_color_brewer(palette="Set1")+
  scale_linetype_manual(values=c(3,2,1))+
  xlab("Number of participants")+
  ylab("Expected Information Gain")+
  theme_paper()+
  guides(color=F, linetype = F)

#ggsave("writing/nips2016/img/legend.pdf", width = 5, height = 3.5)
```

Actual information gain vs. Expected information gain (using empirical Ns)

```{r, fig.height=3.5, fig.width=7}

d<-read.csv("../data/coins-eig-vs-aig-empiricalN-ignorance.csv")

d.tidy <- d %>% 
  filter(models != "fairVmarkov") %>%
  mutate(models = factor(models, 
                  levels = c("fairVbias", "biasVmarkov",
                                     "fairVbiasVmarkov"),
                  labels = c(
                    "fair vs. bias",
                    "bias vs. markov",
                    "fair vs. bias vs. markov")))
  


labels <- data.frame(x = c(0.1, 0.5, 0.4), 
                    y = c(0.6, 0.1, 0.8),
                    m = c("fair vs. bias",
                    "bias vs. markov",
                    "fair vs. bias vs. markov")
                    ) %>%
  group_by(m) %>%
  mutate(label = with(d.tidy %>% filter(models==m),
                          corr_eqn(eig,aig))) %>%
  ungroup() %>%
  rename(models = m)

# spearman correlations
d.tidy %>%
  group_by(models) %>%
  summarize(cor(aig,eig, method='spearman'))

  
ggplot(d.tidy, aes(x = eig, y = aig, 
                #fill=models, 
                label=experiment))+
  #geom_jitter(shape=21, size=3)+
  geom_jitter(size=2)+
  geom_smooth(method='lm', color='black', lty=2, alpha=0.6, size = 0.3)+
    #geom_point(shape = 21, position=position_jitter())+
    geom_text(data=labels, aes(x=x, y=y, label=label), parse = TRUE)+
    #geom_text(check_overlap = TRUE, position=position_jitter())+
    facet_wrap(~models, scales='free')+
    xlab("Expected Information Gain")+
    ylab("Actual Information Gain")+
    guides(fill=F)+
  coord_fixed(ratio=1)+
  theme_paper()

#ggsave("~/Documents/research/oed/oed/writing/nips2016/img/coin_eig_aig_scatter_noText.pdf", height = 3.5, width = 7)

```

# Webppl Models for coins

#### Fair coin model

```{r}
fairCoin <- "
var fairSingle = cache(function(sequence) {
    Infer({method:'enumerate'}, function() {
        return flip()
    })
})
fairSingle('no seq necessary')
"
```

#### Bias coin model
```{r}
biasCoin <- "
var coinWeights = [0.01, 0.10, 0.20, 0.30, 0.40, 0.50, 
                        0.60, 0.70, 0.80, 0.90, 0.99];


// assumes a.length == b.length
var arraysEqual = function(as,bs) {
    return all(idF, map2(function(a, b) { return a === b }, as, bs))
}


var biasCoin = function(sequence) {
  Infer({method:'enumerate'}, function(){
      var p = uniformDraw(coinWeights);
      var sampled = repeat(sequence.length, function() { flip(p) })
      condition(arraysEqual(sampled, sequence))
      return flip(p)
  })
}

biasCoin(map(function(x){return x==1}, input_seq))
"
```

### Markov coin model

```{r}
markovCoin<-"
var coinWeights = [0.01, 0.10, 0.20, 0.30, 0.40, 0.50, 
                        0.60, 0.70, 0.80, 0.90, 0.99];
// assumes a.length == b.length
var arraysEqual = function(as,bs) {
    return all(idF, map2(function(a, b) { return a === b }, as, bs))
}

var markovCoin = function(sequence) {
    Infer({method:'enumerate'}, function(){
        var transitionProb = uniformDraw(coinWeights);
        var generateSequence = function(n, flipsSoFar) {
            if (flipsSoFar.length == n) {
                return flipsSoFar;
            } else {
                var lastFlip = last(flipsSoFar);
                return generateSequence(n, append(flipsSoFar,
                                flip(transitionProb) ? !lastFlip : lastFlip))
            }
        }

        var firstCoin = flip();
        var sampled = generateSequence(sequence.length, [firstCoin]);
        condition(arraysEqual(sampled, sequence));

        return flip(transitionProb) ? !last(sampled) : last(sampled);
    })
}

markovCoin(map(function(x){return x==1}, input_seq))
"
```

Predictions

```{r}
# opt_exp =  c(1,1,1,1)
# penopt_exp = c(1,1,1,0)
# penopt_exp2 = c(1,0,1,0)
# 
# model_predictions<-bind_rows(
#    webppl(model_code = fairCoin, 
#           model_packages = c("~/Documents/research/oed/webppl-oed/"),
#           data = opt_exp, data_var = 'input_seq') %>%
#     mutate(model = 'fair',
#            expt = 'HHHH'),
#    webppl(model_code = biasCoin,    
#           model_packages = c("~/Documents/research/oed/webppl-oed/"),
#          data = opt_exp, data_var='input_seq') %>%
#     mutate(model = 'bias',
#            expt = 'HHHH'),
#    webppl(model_code = markovCoin,
#           model_packages=c("~/Documents/research/oed/webppl-oed/"),
#           data = opt_exp, 
#           data_var='input_seq') %>%
#     mutate(model = 'markov',
#            expt = 'HHHH'),
#    webppl(model_code = fairCoin, model_packages=c("~/Documents/research/oed/webppl-oed/"),
#          data = penopt_exp, data_var='input_seq') %>%
#     mutate(model = 'fair',
#            expt = 'HHHT'),
#    webppl(model_code = biasCoin, model_packages=c("~/Documents/research/oed/webppl-oed/"),
#          data = penopt_exp, data_var='input_seq') %>%
#     mutate(model = 'bias',
#            expt = 'HHHT'),
#    webppl(model_code = markovCoin, model_packages=c("~/Documents/research/oed/webppl-oed/"),
#          data = penopt_exp, data_var='input_seq') %>%
#     mutate(model = 'markov',
#            expt = 'HHHT'),
#    webppl(model_code = fairCoin, model_packages=c("~/Documents/research/oed/webppl-oed/"),
#          data = penopt_exp2, data_var='input_seq') %>%
#     mutate(model = 'fair',
#            expt = 'HTHT'),
#    webppl(model_code = biasCoin, model_packages=c("~/Documents/research/oed/webppl-oed/"),
#          data = penopt_exp2, data_var='input_seq') %>%
#     mutate(model = 'bias',
#            expt = 'HTHT'),
#    webppl(model_code = markovCoin, model_packages=c("~/Documents/research/oed/webppl-oed/"),
#          data = penopt_exp2, data_var='input_seq') %>%
#     mutate(model = 'markov',
#            expt = 'HTHT')
# )
```

```{r}
# mp<-model_predictions %>% 
#   filter(support==TRUE) %>% 
#   mutate(model = factor(model, levels=c("fair", "bias", "markov")),
#          expt = factor(expt, levels=c("HTHT", "HHHT", "HHHH")))
# 
# ggplot(mp, aes(x=model, y = probs, fill=expt))+
#   geom_bar(stat='identity', position=position_dodge())+
#   facet_wrap(~expt)+
#   ylab("Predicted probability of H")+
#   xlab("Model")+
#   theme_paper()+
#   scale_fill_brewer(palette="Set1")+
#   guides(fill=F)
# 
# 
# ggsave("~/Documents/research/oed/oed/writing/nips2016/img/coin_predictions.pdf", width = 7, height =3.5)

```