```{r}
library(jsonlite)
library(dplyr)
library(ggplot2)
library(directlabels)
library(memoise)
library(readr)
theme_set(theme_classic(16) +
theme(
    axis.line.x = element_line(colour = "black"),
    axis.line.y = element_line(colour = "black")
  ))
```

# histogram of EIG values

read in json files

```{r}
search.data.dir = "../data/categories-search/"
json.filenames = (function(x) { paste0(search.data.dir, x[grepl("json", x)]) })(list.files(search.data.dir))
dfs = Map(fromJSON, json.filenames)
```

extract eigs so far
```{r}
eigs = unname(unlist(Map(function(e) { e$EIG }, dfs)))
```

plot
```{r}
d.eig = data.frame(eig = eigs) 

breaks = seq(from = 0, to = 0.09, by = 0.01/2)

d.eigcut = d.eig %>%
  transform(bucket = cut(eig,
                         breaks = breaks,
                         labels = breaks[2:length(breaks)]
                         )) %>%
  transform(bucket = as.numeric(as.character(bucket))) %>%
  group_by(bucket) %>% summarise(count = n())

d.eigcut = d.eigcut %>% transform(Experiment = ifelse(bucket == 0.03, "MS",
                                                      ifelse(bucket == 0.085, "Optimal", "Other")))

d.eigcut$Experiment = factor(d.eigcut$Experiment, levels = levels(d.eigcut$Experiment)[c(2,1,3)])

ggplot(data = d.eigcut) + geom_bar(mapping = aes(x = bucket, y = count, fill = Experiment), stat = 'identity') + 
  ylab("Count") +
  xlab("Expected information gain") + 
  scale_x_continuous(limits = c(0,0.09), breaks = seq(from = 0, to = 0.09, by = 0.09 / 3)) + 
  scale_fill_manual(values = c("MS" = "red2", "Optimal" = "blue", "Other" = "grey60"))
```

# curve of AIGs vs subjects

```{r}
generic.ci_ <- function(x, n = 5000){
    structure(
        quantile(
            replicate(n, mean(sample(x, replace = TRUE),
                              na.rm = TRUE)),
            c(0.025, 0.975)),
        names=c("ci.l","ci.u"))
}

generic.ci <- memoise(generic.ci_)

ci.l <- function(x) {
  generic.ci(x)["ci.l"]
}

ci.u <- function(x) {
  generic.ci(x)["ci.u"]
}
```

todo: optimize CI time
```{r}
aigs = rbind(fromJSON("../data/categories-aig-curve-ms.json"),
             fromJSON("../data/categories-aig-curve-opt.json"))

aigs.agg = aigs %>%
  group_by(ex, n) %>%
  summarise(mean.aig = mean(aig),
            cl = ci.l(aig),
            cu = ci.u(aig)) %>%
  ungroup() %>%
  mutate(ex = factor(ifelse(ex == 'ms', 'MS','Optimal')))

aigs.agg$Experiment = factor(aigs.agg$ex, levels = rev(levels(aigs.agg$ex)))
```

(export as 6x3)
```{r}
qplot(data =  aigs.agg,
      x = n,
      y = mean.aig,
      ymin = cl,
      ymax = cu,
      color = Experiment,
      geom = c('point','errorbar','line')) + ylab("Actual information gain") + xlab("Number of participants") +
  scale_color_manual(values = c("MS" = "red2", "Optimal" = "blue", "Other" = "grey60"))

```

make figure 4b from json:

```{r}
d = fromJSON(txt="../../code/fig4b.json")
```

```{r}
d.agg = d %>%
  group_by(x, n) %>%
  summarise(mean.aig = mean(aig),
            cl = ci.l(aig),
            cu = ci.u(aig)) %>%
  ungroup() %>%
  mutate(x = factor(ifelse(x == 'ms', 'MS','Optimal'))) %>%
  transform(Experiment = factor(x, levels = rev(levels(x))))
```

```{r 4b, fig.width = 6, fig.height = 3}
qplot(data =  d.agg,
      x = n,
      y = mean.aig,
      ymin = cl,
      ymax = cu,
      color = Experiment,
      geom = c('point','errorbar', 'line')) + ylab("Actual information gain") + xlab("Number of participants") +
  scale_color_manual(values = c("MS" = "red2", "Optimal" = "blue", "Other" = "grey60"))
```


# examine optimal experiment

```{r}
which.max(eigs) # 34
#print(dfs[[3]]$x$as[[4]])
#print(dfs[[3]]$x$bs[[4]])

print('as')
print(apply(ifelse(dfs[[3]]$x$as[[4]], 1, 0), 1, function(x) { paste(x, collapse = "" )}))
print('')
print('bs')
print(apply(ifelse(dfs[[3]]$x$bs[[4]], 1, 0), 1, function(x) { paste(x, collapse = "" )}))

```


# compare optimal and ms model predictions

```{r}
dpred = read_csv('../data/categories-prototype-exemplar-predictions.csv',
                 col_types = cols(stim = col_character())) 
```


```{r}
d.viz = dpred %>% transform(model = ifelse(str_sub(model, 1, 1) == 'e', 'X', 'P')) %>% transform(experiment = c(ms = 'MS', opt = 'Optimal')[experiment])

dpred.lines = d.viz %>% select(-prediction5k) %>% spread(model, prediction) %>% mutate(catx = (X < 0.5), catp = (P < 0.5), qual.diff = (catx != catp))



ggplot(data = d.viz, mapping = aes(x = stim)) +
  facet_grid(. ~ experiment) +
    geom_linerange(data = dpred.lines,
                 mapping = aes(ymin = X,ymax = P)) +
  geom_text(mapping = aes(x = stim,
                           y = prediction,
                           label = model),
            color = 'steelblue3',
            size = 4) + 
  geom_hline(yintercept = 0.5, color = 'gray50') + ylab("Model predictions") + xlab("Stimulus") +
  theme(axis.text.x = element_text(angle = -45, size = 10, hjust = 0))

```

```{r}
BinToDec <- function(x) 
    sum(2^(which(rev(unlist(strsplit(as.character(x), "")) == 1))-1))

dpred.lines = dpred %>% select(-prediction5k) %>% spread(model, prediction) %>%
  mutate(stim.num = sapply(stim, BinToDec),
         x = ifelse(experiment == 'ms', 0, 0) + stim.num)

ggplot(mapping = aes(x = stim)) +
    geom_errorbar(data = dpred.lines,
                  mapping = aes(x = x,
                                color = experiment,
                                ymin = exemplar,ymax = prototype)) +
  geom_hline(yintercept = 0.5, color = 'gray50')
```


absolute values of predictions are obscuring differences




```{r}
dpred.lines = dpred %>% select(-prediction5k) %>% spread(model, prediction) %>%
  mutate(diff = abs(exemplar - prototype))

ggplot() +
  geom_point(data = dpred.lines %>% select(-exemplar, -prototype) %>% spread(experiment, diff),
             mapping = aes(x = ms,y = opt)) + geom_abline() + xlim(0, 0.16) + ylim(0, 0.16)

ggplot() +
  geom_bar(data = dpred.lines %>% rename(Experiment = experiment) %>% transform(Experiment = ifelse(Experiment == 'ms', 'MS', 'Optimal')),
           mapping = aes(x = stim, y = diff, fill = Experiment), stat = 'identity', position = 'dodge') + 
  xlab("Object") + 
  ylab("Absolute difference\nin model predictions") + 
  theme_paper() + 
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  scale_fill_manual(values = c("MS" = "indianred", "Optimal" = "steelblue2"))
```








