---
title: "paper figures"
author: "mhtess and louyang"
date: "May 11, 2016"
output:
  html_document:
    self_contained: no
  pdf_document: default
---

# Packages, helper functions, and plot theme

```{r echo=F}
library(jsonlite)
library(ggplot2)
library(dplyr)
library(directlabels)
library(memoise)

source('theme_paper.R')

corr_eqn <- function(x,y, digits = 2) {
  corr_coef <- round(cor(x, y)^2, digits = digits)
  paste("italic(r^2) == ", corr_coef)
}

generic.ci_ <- function(x, n = 5000){
    structure(
        quantile(
            replicate(n, mean(sample(x, replace = TRUE),
                              na.rm = TRUE)),
            c(0.025, 0.975)),
        names=c("ci.l","ci.u"))
}

generic.ci <- memoise(generic.ci_)

ci.l <- function(x) {
  generic.ci(x)["ci.l"]
}

ci.u <- function(x) {
  generic.ci(x)["ci.u"]
}
```

# Coins

```{r 1b, dev="pdf", fig.width = 11, fig.height = 4}
d = fromJSON(txt="../code/fig1b.json") %>%
  mutate(comparison = factor(comparison,
                  levels = c("fair-bias", "bias-markov", "threeway"),
                  labels = c(
                    "Fair vs. Bias",
                    "Bias vs. Markov",
                    "Fair vs. Bias vs. Markov"
                  )))

ggplot(data = d, aes(x = experiment, y = eig))+
    geom_bar(stat='identity', position=position_dodge())+
    coord_flip()+
    facet_wrap(~comparison)+
    ylab("Expected Information Gain from 20 participants")+
    xlab("Experiment")+
    guides(fill=F)+
  theme_paper()
```


making figure 2a from fig2a.json:

```{r 2a, dev="pdf", fig.width = 7, fig.height = 3.5}
d = fromJSON(txt="../code/fig2a.json") %>%
  mutate(model = factor(model, levels=c("fair", "bias", "markov")),
         experiment = factor(experiment, levels=c("HTHT", "HHHT", "HHHH")))

ggplot(data = d) +
  facet_wrap(~ experiment) +
  geom_bar(mapping = aes(x = model,
                         y = probHeads,
                         fill = experiment),
           stat = 'identity') +
  xlab("Model") +
  scale_x_discrete(labels = c("Fair", "Bias", "Markov")) +
  ylab("Predicted probability of H") +
  scale_fill_brewer(palette="Set1") +
  guides(fill=F) +
  theme_paper()
```


making figure 2b from fig2b.json:

```{r 2b, dev="pdf", fig.width=5, fig.height=3.5}
d = fromJSON(txt="../code/fig2b.json") %>%
  rename(Experiment = experiment) %>%
  mutate(Experiment = factor(Experiment, levels=c("HTHT", "HHHT", "HHHH")))

p = ggplot(data = d) +
  geom_line(mapping = aes(x = n,
                          y = EIG,
                          color = Experiment,
                          linetype=Experiment),
            size=1.3) +
  scale_color_brewer(palette="Set1") +
  scale_linetype_manual(values=c(3,2,1)) +
  xlab("Number of participants") +
  ylab("Expected Information Gain") +
  xlim(1,33) +
  theme_paper() +
  guides(color=F, linetype = F)

direct.label(p,
             list("last.points", cex = 1.1))
```

making figure 3 from fig3.json:

```{r 3, dev="pdf", fig.width=10.8, fig.height=4.05}
d = fromJSON(txt="../code/fig3.json")

d$comparison = factor(d$comparison, levels = c("fair-bias","bias-markov","fair-bias-markov"))

comparison_labeller = function(labels) {
  labels %>% transform(comparison = c("fair-bias" = "Fair vs. Bias",
                                      "bias-markov" = "Bias vs. Markov",
                                      "fair-bias-markov" = "Fair vs. Bias vs. Markov")[as.character(comparison)])
}

labels = d %>%
  group_by(comparison) %>%
  summarise(label = corr_eqn(eig,aig)) %>%
  merge(data.frame(x = c(0.1, 0.5, 0.4),
                   y = c(0.6, 0.1, 0.8),
                   comparison = c("fair-bias","bias-markov","fair-bias-markov")))

ggplot(data = d, mapping = aes(x = eig, y = aig)) +
  facet_wrap( ~ comparison, scales = 'free', labeller = comparison_labeller) +
  stat_smooth(method='lm', color='black', lty=2, alpha=0.6, size = 0.3) +
  geom_point(size = 2, alpha = 0.6) +
  geom_text(data=labels, aes(x=x, y=y, label=label), parse = TRUE)+
  xlab("Expected information gain") +
  ylab("Actual information gain") +
  scale_y_continuous(limits = c(-0.1,1.2), breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.2)) +
  theme_paper()
```

# Categories

```{r 4a, dev="pdf", fig.width = 6, fig.height = 3}
ds = Map(function(x) { fromJSON(paste0("../code/fig4a/",x)) }, list.files("../code/fig4a"))

eigs = unname(unlist(Map(function(e) { e$EIG }, ds)))

d.eig = data.frame(eig = eigs)

breaks = seq(from = 0, to = 0.09, by = 0.01/2)

d.eigcut = d.eig %>%
  transform(bucket = cut(eig,
                         breaks = breaks,
                         labels = breaks[2:length(breaks)]
                         )) %>%
  transform(bucket = as.numeric(as.character(bucket))) %>%
  group_by(bucket) %>% summarise(count = n())

d.eigcut = d.eigcut %>% transform(Experiment = ifelse(bucket == 0.03, "MS",
                                                      ifelse(bucket == max(d.eigcut$bucket), "Optimal", "Other")))

d.eigcut$Experiment = factor(d.eigcut$Experiment, levels = levels(d.eigcut$Experiment)[c(2,1,3)])

ggplot(data = d.eigcut) + geom_bar(mapping = aes(x = bucket, y = count, fill = Experiment), stat = 'identity') +
  ylab("Count") +
  xlab("Expected information gain") +
  theme_paper() +
  scale_x_continuous(limits = c(0,0.09), breaks = seq(from = 0, to = 0.09, by = 0.09 / 3)) +
  scale_fill_manual(breaks = c("Optimal", "MS"), values = c("MS" = "red2", "Optimal" = "blue", "Other" = "grey60"))
```


```{r 4b, dev="pdf", fig.width = 6, fig.height = 3}
d = fromJSON(txt="../code/fig4b.json")

d.agg = d %>%
  group_by(x, n) %>%
  summarise(mean.aig = mean(aig),
            cl = ci.l(aig),
            cu = ci.u(aig)) %>%
  ungroup() %>%
  mutate(x = factor(ifelse(x == 'ms', 'MS','Optimal'))) %>%
  transform(Experiment = factor(x, levels = rev(levels(x))))

qplot(data =  d.agg,
      x = n,
      y = mean.aig,
      ymin = cl,
      ymax = cu,
      color = Experiment,
      geom = c('point','errorbar', 'line')) + ylab("Actual information gain") + xlab("Number of participants") +
  scale_color_manual(values = c("MS" = "red2", "Optimal" = "blue", "Other" = "grey60")) + theme_paper()
```


